# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gibbs_imp <- function(data, data_indx, mu_vec, cond_param) {
    .Call('_mvnimpute_Gibbs_imp', PACKAGE = 'mvnimpute', data, data_indx, mu_vec, cond_param)
}

param_calc <- function(data) {
    .Call('_mvnimpute_param_calc', PACKAGE = 'mvnimpute', data)
}

single_imputation <- function(data) {
    .Call('_mvnimpute_single_imputation', PACKAGE = 'mvnimpute', data)
}

SWP <- function(data, swp_indx) {
    .Call('_mvnimpute_SWP', PACKAGE = 'mvnimpute', data, swp_indx)
}

cond_param <- function(data) {
    .Call('_mvnimpute_cond_param', PACKAGE = 'mvnimpute', data)
}

