# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gibbs_imp <- function(data, data_indx, mu_vec, cond_param) {
    .Call('_mvnimpute_Gibbs_imp', PACKAGE = 'mvnimpute', data, data_indx, mu_vec, cond_param)
}

#' Calculate the CC and AC parameters
#'
#' This function calculates the complete cases (CC) and available cases (AC) mean and variance values,
#' excluding the missing and censored values.
#'
#' @param data a list object including the two matrices for the lower and upper bounds of the data.
#' @export
param_calc <- function(data) {
    .Call('_mvnimpute_param_calc', PACKAGE = 'mvnimpute', data)
}

#' Single imputation function
#'
#' This function performs single imputation of the data using the available cases mean and variance values
#' excluding the missing and censored values.
#'
#' @param data a list including the matrices for the lower and upper bounds of the data.
#' @export
single_imputation <- function(data) {
    .Call('_mvnimpute_single_imputation', PACKAGE = 'mvnimpute', data)
}

SWP <- function(data, swp_indx) {
    .Call('_mvnimpute_SWP', PACKAGE = 'mvnimpute', data, swp_indx)
}

cond_param <- function(data) {
    .Call('_mvnimpute_cond_param', PACKAGE = 'mvnimpute', data)
}

